AplikacjaMVC/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AplikacjaMVC.Models;

namespace AplikacjaMVC.Controllers
{
    public class CarsController : Controller
    {
        private CarDBContext db = new CarDBContext();

        // GET: Cars
        [Authorize(Roles = "Admin, SuperUser, User")]
        public ActionResult Index()
        {
            return View(db.Cars
                .Include(i => i.Seller)
                .Include(i => i.Engine)
                .ToList());
        }

        // GET: Cars/Details/5
        [Authorize(Roles = "Admin, SuperUser, User")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars
                      .Include(i => i.Seller)
                      .Include(i => i.Engine)
                      .SingleOrDefault(x => x.ID == id);

            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // GET: Cars/Create
        [Authorize(Roles = "Admin, SuperUser")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, SuperUser")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Brand,Model,ProductionYear,Color,VIN,Mileage,Photo,Price,Seller,Engine")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Cars.Add(car);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(car);
        }

        // GET: Cars/Edit/5
        [Authorize(Roles = "Admin, SuperUser")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars
                      .Include(i => i.Seller)
                      .Include(i => i.Engine)
                      .SingleOrDefault(x => x.ID == id);

            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, SuperUser")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Brand,Model,ProductionYear,Color,VIN,Mileage,Photo,Price,Seller,Engine")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(car);
        }

        // GET: Cars/Delete/5
        [Authorize(Roles = "Admin, SuperUser")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars
                      .Include(i => i.Seller)
                      .Include(i => i.Engine)
                      .SingleOrDefault(x => x.ID == id);

            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: Cars/Delete/5
        [Authorize(Roles = "Admin, SuperUser")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Car car = db.Cars
                      .Include(i => i.Seller)
                      .Include(i => i.Engine)
                      .SingleOrDefault(x => x.ID == id);
            

            db.Cars.Remove(car);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AplikacjaMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AplikacjaMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "ASP .NET Aplication by Artur Borkowski.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Artur Borkowski";

            return View();
        }
    }
}

AplikacjaMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About this project";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Application created during studies in Polish-Japanese Academy of Information Technology by Artur Borkowski (s12020) 
    under the supervision of dr Tomasz Borzyszkowski.</p>

AplikacjaMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Polsko-Japońska Akademia Technik Komputerowych<br />
    ul. Brzegi 55 <br />
    Gdańsk, 80-045 <br />
    <abbr title="Phone">P:</abbr>
    (+48 58) 683-59-87
</address>

<address>
    <strong>Student:</strong>   <a href="mailto:s12020@pjwstk.edu.pl">s12020@pjwstk.edu.pl</a><br />
    <strong>Teacher:</strong> <a href="mailto:t.borzyszkowski@pjwstk.edu.pl">t.borzyszkowski@pjwstk.edu.pl</a>
</address>

AplikacjaMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Auto-Borek</h1>
    <p class="lead">Dealer of a used cars in Gdansk. You can find here a car of your dream for a decent money!</p>
    <p>
        @Html.ActionLink(HttpUtility.HtmlDecode("Explore &raquo;"), "Index", "Cars", new { area = "" }, new { @class = "btn btn-primary btn-lg" })
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Find your car</h2>
        <p>
            Here you can start looking for your car. We have plenty of offers among which you will certainly find the one suitable for you. 
        </p>
        <p>
            @Html.ActionLink(HttpUtility.HtmlDecode("Buy a car &raquo;"), "Index", "Cars", new { area = "" }, new { @class = "btn btn-default" })
        </p>
    </div>
    <div class="col-md-4">
        <h2>Sell your car</h2>
        <p>Already have a car but you don't like it anymore? Why don't you sell it? We would love to buy it from you! After all you can buy a new one from us!</p>
        <p>
            @Html.ActionLink(HttpUtility.HtmlDecode("Sell a car &raquo;"), "Create", "Cars", new { area = "" }, new { @class = "btn btn-default" })
        </p>
    </div>
    <div class="col-md-4">
        <h2>About us</h2>
        <p>We are well-known used car dealer in Gdansk with over 15 years of experience. We buy, we sell and we make people happy.</p>
        <p>
            @Html.ActionLink(HttpUtility.HtmlDecode("More about us &raquo;"), "About", "Home", new { area = "" }, new { @class = "btn btn-default" })
        </p>
    </div>
</div>